### ISSUE TITLE
Правильный слайдер

### ISSUE THREAD

**Issue by solarrust** [doka-guide/content#2730]
Простая галерея баннеров или слайдов, реализованная с учётом адаптива и доступности.

**Comment by AnnaBaraulina** [comment]
Привет! Я бы хотела взять! Если подскажете, какие технологии сюда обязательно включить, чтобы максимально соответствовать трендам, буду благодарна!

**Comment by AnnaBaraulina** [comment]
Класс, спасибо большое!15.01.2024, 20:58, "Tatiana Fokina" ***@***.***>:

Привет! Я бы хотела взять! Если подскажете, какие технологии сюда обязательно включить, чтобы максимально соответствовать трендам, буду благодарна!

Привет! Могу подкинуть полезных ссылок со слайдерами и каруселями. В примерах с каруселями почти всё то же, что слайдерами, надо только выпилить автопереключение и кнопку паузы и старта.

A Content Slider.
A Step-By-Step Guide To Building Accessible Carousels.
Доступная карусель, доклад Юлии Долгун. Если больше нравится видеоформат.
Carousel (Slide Show or Image Rotator) Pattern. Описано как в теории работает компонент, включая навигацию с клавиатуры.
Auto-Rotating Image Carousel Example with Buttons for Slide Control.


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
-- ---Kind regards,Ann Baraulina+79998030122

**Comment by solarrust** [comment]
@AnnaBaraulina Привет! Пинг по этой задаче. Нужна ли помощь?
